### PR TITLE
Issue 42 - Avoids javascript error

### LINKED ISSUE #42: Error in TinyMCE plugin if the property icon_visibility is disabled.
If property ```portal_properties/site_properties/icon_visibility``` is disabled, and created a Embedder, after when we add a document, clicking in sc.embedder button in TinyMCE, and so click in current folder, the js error occurs:

```javascript
TypeError: data.items[i].icon is null

if (data.items[i].icon.length) {

scembedder.js (line 452)
```
Then, the folder contents are not listed.

The line in question is [this](https://github.com/simplesconsultoria/sc.embedder/blob/master/src/sc/embedder/skins/tinymce/scembedder/js/scembedder.js#L452).

A fix is necessary like [here](https://github.com/simplesconsultoria/sc.embedder/commit/935a4e71534da2e9b86dc692497ea1169accd39e).

### PR DESCRIPTION
**Pull request by rodfersou**
closes #42

### CODE REVIEW

**Comment by rodfersou** [comment]
@hvelarde @idgserpro is it what you need?

**Comment by rodfersou** [comment]
We have an error with one provider at tests http://vjs.zencdn.net/oceans-clip.webm http://vjs.zencdn.net

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>B80D0C615D26D6DF</RequestId>
<HostId>
qpLhJZVbMqlP/RDNeew3BXL50EWDstIWfJmkp+d73tV7Z+wni6cKdXk32GYPf92p6yPemRa94aA=
</HostId>
</Error>
```

Should I remove these tests?

**Comment by hvelarde** [comment]
I think so

**Comment by idgserpro** [comment]
@rodfersou this solved the problem of listing the contents. However, when loading the popup, the js error occurs:

```javascript
TypeError: tinymce.dom.Event._add is not a function

...a.editor.windowManager.close(window);tinymce=tinyMCE=a.editor=a.params=a.dom=a.d...

tiny_mce_popup.js (linha 5)
```

**Comment by hvelarde** [comment]
@idgserpro a RF test would be useful here.

**Comment by rodfersou** [comment]
@idgserpro I fix the tests error, need to check your exception, any advise on how to see the problem?

**Comment by idgserpro** [comment]
When you click on the button of sc.embedder in TinyMCE, the javascript error occurs. Seems a mismatch of tiny_mce_popup.js file with TinyMCE file (tiny_mce.js).

**Comment by idgserpro** [comment]
@hvelarde the error https://github.com/simplesconsultoria/sc.embedder/pull/43#issuecomment-180311012 will not be treated?

**Comment by idgserpro** [comment]
Sorry. I tested here and the error https://github.com/simplesconsultoria/sc.embedder/pull/43#issuecomment-180311012 no longer occurs.

**Pull request merged**
