### PR TITLE
Add upgrade step to cook JS resources

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by hvelarde** [comment]
@idgserpro please test and let me know if now we are ready for the release.

**Comment by idgserpro** [comment]
@hvelarde cook resources the cookie doesn't help here. [Same problem](https://github.com/collective/collective.cover/issues/613).

An error occurred while starting the instance:

```bash
./bin/instance fg
2016-03-23 10:03:24 INFO ZServer HTTP server started at Wed Mar 23 10:03:24 2016
	Hostname: 0.0.0.0
	Port: 8080
Traceback (most recent call last):
  File "/home/user/git/sc.embedder/parts/instance/bin/interpreter", line 281, in <module>
    execfile(__file__)
  File "/home/user/cache-python/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/user/cache-python/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/user/cache-python/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/__init__.py", line 86, in prepare
    self.startZope()
  File "/home/user/cache-python/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/__init__.py", line 262, in startZope
    Zope2.startup()
  File "/home/user/cache-python/eggs/Zope2-2.13.23-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/user/cache-python/eggs/Zope2-2.13.23-py2.7.egg/Zope2/App/startup.py", line 118, in startup
    load_zcml()
  File "/home/user/cache-python/eggs/Zope2-2.13.23-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/home/user/cache-python/eggs/Zope2-2.13.23-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 649, in file
    include(context, name, package)
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/user/pythons/python279/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/user/pythons/python279/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/user/pythons/python279/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 341, in start_element_ns
    AttributesNSImpl(newattrs, qnames))
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 232, in startElementNS
    self.context.begin(name, data, info)
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 555, in begin
    self.stack.append(self.stack[-1].contained(__name, __data, __info))
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 856, in contained
    return RootStackItem.contained(self, name, data, info)
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 724, in contained
    factory = self.context.factory(self.context, name)
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 501, in factory
    raise ConfigurationError("Unknown directive", ns, n)
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/user/git/sc.embedder/parts/instance/etc/site.zcml", line 15.2-15.55
    ZopeXMLConfigurationError: File "/home/user/git/sc.embedder/parts/instance/etc/package-includes/002-sc.embedder-configure.zcml", line 1.0-1.55
    ZopeXMLConfigurationError: File "/home/user/git/sc.embedder/src/sc/embedder/configure.zcml", line 27.4
    ConfigurationError: ('Unknown directive', u'http://namespaces.zope.org/z3c', u'widgetTemplate')
```

I think [that's](https://github.com/simplesconsultoria/sc.embedder/commit/263758ea6b0648cf42b4c188ceaf80a1f2788085#diff-86c62d41bea703415fdc885644a2d0ecL11) what caused this error.

**Comment by hvelarde** [comment]
yes, I removed that line because I want to explicitly add the list of packages there, but I get no error on the tests.

I think that directive probably comes from z3c.form; I'll check it.

**Comment by hvelarde** [comment]
@idgserpro must have been solved in 790d561849562d6f32adb2fd13ec7278a4c730d4.

let me know if you find further problems.

**Comment by idgserpro** [comment]
@hvelarde  It's still necessary include in configure.zcml:

```xml
    <include package="five.grok" />
    <include package="five.grok" file="meta.zcml" />
    <include package="Products.CMFCore" file="permissions.zcml" />
```

**Comment by hvelarde** [comment]
feel free to commit and let me know when I can make a release.

**Comment by hvelarde** [comment]
@idgserpro done in 4d8b1ab08216eccd07b306bcb32073972830d1c5; ready now?

**Comment by idgserpro** [comment]
@hvelarde all ok now!

:+1:

**Comment by hvelarde** [comment]
I'll do it tomorrow; sorry, but it's beach time now ;-)

**Comment by hvelarde** [comment]
@idgserpro release 1.1b1 just went out of the oven: https://pypi.python.org/pypi/sc.embedder/1.1b1

**Comment by idgserpro** [comment]
@hvelarde  thanks! I will update in IDG.

**Pull request merged**
